[font]
size = 16.0

[font.normal]
family = "Monospace"
style = "Regular"

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Blod Italic"

[font.italic]
family = "Monospace"
style = "Italic"
