[[language]]
name = "rust"

[language-server.rust-analyzer.config]
imports.granularity.group = "module"
imports.prefix = "crate"
diagnostics.experimental.enable = true

[[language]]
name = "go"

[language-server.gopls.config]
semanticTokens = true
gofumpt = true
analyses = { "shadow" = true, "fieldalignment" = true, "unusedvariable" = true, "useany" = true }
usePlaceholders = true
staticcheck = true
vulncheck = "Imports"
hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true }

[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
args = [ "--background-index", "--compile-commands-dir=build", "-j=8", "--clang-tidy", "--all-scopes-completion", "--completion-style=detailed", "--function-arg-placeholders", "--header-insertion=iwyu", "--pch-storage=memory", "--malloc-trim", "--offset-encoding=utf-8" ]
config = { "fallbackFlags" = [ "-std=c++17", "-Wc++17-extensions" ] }
