-- https://github.com/nvim-treesitter/nvim-treesitter#supported-languages
local options = {
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "comment",
    "cpp",
    "diff",
    "dockerfile",
    "gitignore",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "gpg",
    "http",
    "html",
    "ninja",
    "json",
    "json5",
    "lua",
    "make",
    "markdown",
    "llvm",
    "lua",
    "luadoc",
    "python",
    "regex",
    "sql",
    "rust",
    "yaml",
    "toml",
    "css",
  },
}

return options
