[packages.darwin]
mas = [
    1549159979, # uPic
    6452276577, # DockX
    462058435, # Microsoft Excel
    6467176005, # 1Break
    1630034110, # Bob
    1024640650, # CotEditor
    462054704, # Microsoft Word
    462062816, # Microsoft PowerPoint
    1189898970, # 企业微信
    1484048379, # 腾讯会议
    1449962996, # 腾讯柠檬清理(Lite)
    6698876601, # Folder Preview
]
brews = [
    "bash-completion@2",
    "bat",
    "bottom",
    "chezmoi",
    "cmake",
    "colima",
    "curl",
    "d2",
    "direnv",
    "docker",
    "docker-compose",
    "docker-buildx",
    "duckdb",
    "dwarf",
    "eza",
    "fd",
    "ffmpeg",
    "ffmpegthumbnailer",
    "git",
    "git-delta",
    "git-lfs",
    "gnupg",
    "go",
    "goose",
    "gopass",
    "gopls",
    "graphviz",
    "helix",
    "helm",
    "hexyl",
    "hurl",
    "hyperfine",
    "imagemagick",
    "jq",
    "just",
    "k9s",
    "kind",
    "kubernetes-cli",
    "kubie",
    "less",
    "lld",
    "luarocks",
    "mas",
    "miniserve",
    "navi",
    "ninja",
    "onefetch",
    "openjdk@11",
    "openssh",
    "openssl",
    "ouch",
    "pinentry",
    "poppler",
    "qemu",
    "ripgrep",
    "rmtrash",
    "ruff",
    "rustup",
    "sccache",
    "sevenzip",
    "sqlfluff",
    "starship",
    "stylua",
    "tokei",
    "topgrade",
    "vegeta",
    "yazi",
    "zoxide",
]
casks = [
    "appcleaner",
    "clash-verge-rev",
    "dbeaver-community",
    "font-iosevka-nerd-font",
    "font-iosevka-term-nerd-font",
    "font-noto-serif-cjk-sc",
    "font-symbols-only-nerd-font",
    "google-chrome",
    "iina",
    "jordanbaird-ice",
    "maccy",
    "obsidian",
    "raycast",
    "steam",
    "visual-studio-code",
    "wezterm",
    "xld",
    "zed",
    "zotero",
]
