name: Manual workflow

on:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install bat
      run: sudo apt install bat
    - name: Install dotfiles
      run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --no-tty -v --no-pager --keep-going --debug oliverdding --apply --promptDefaults
    - name: Check system
      run: ./bin/chezmoi doctor --keep-going --no-pager --no-tty -v --debug
